import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || path.join(os.homedir(), '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const data = path.join(os.tmpdir(), 'harness-composer-redesign-20260918');
const workspace = path.join(data, 'workspace'); fs.mkdirSync(workspace, { recursive: true });
const ticket = execFileSync('.venv/Scripts/harness.exe', ['--data-dir', data, 'pair'], { encoding: 'utf8' }).trim();
const browser = await chromium.launch({channel:'msedge', headless:true});
const context = await browser.newContext({viewport:{width:1280,height:900}});
const page = await context.newPage();
page.setDefaultTimeout(10000);
const checks = [], errors = [];
page.on('pageerror', e => errors.push(e.message));
const check = (name) => { checks.push(name); console.log('PASS '+name); };
try {
  await page.goto('http://127.0.0.1:8896/#launch='+encodeURIComponent(ticket));
  await page.getByRole('button', {name:'添加项目'}).click();
  await page.getByLabel('项目名称').fill('输入框验收 '+Date.now());
  await page.getByLabel('源文件夹 1', {exact:true}).fill(workspace);
  await page.getByRole('button', {name:'保存并提交',exact:true}).click();
  await page.getByRole('button',{name:'＋ 新建第一个会话',exact:true}).last().click();
  await page.getByRole('button',{name:'重命名',exact:true}).waitFor();
  await page.getByRole('button',{name:'添加图片或文件',exact:true}).waitFor({state:'visible'});
  const editor = page.getByRole('textbox',{name:'消息输入框',exact:true});
  await editor.fill('前文后文');
  await editor.press('Home'); await editor.press('ArrowRight'); await editor.press('ArrowRight');
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAFElEQVR4nGNsWpDCgA0wYRUdtBIANNkBliiA1eMAAAAASUVORK5CYII=';
  const pasteImage = async (name='示意图片.png') => editor.evaluate((el, {png,name}) => {
    const data = new DataTransfer(); data.items.add(new File([Uint8Array.from(atob(png), c=>c.charCodeAt(0))],name,{type:'image/png'}));
    el.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData:data}));
  },{png,name});
  await pasteImage();
  await page.locator('.inline-attachment.ready').waitFor();
  let order = await editor.evaluate(el=>Array.from(el.childNodes).map(n=>n.nodeType===3?n.textContent:n.querySelector('.attachment-name')?.textContent));
  assert.deepEqual(order,['前文','示意图片.png','后文']);
  assert.equal(await page.locator('.inline-editor').count(),1);
  check('paste image at middle cursor, upload fills the inline filename chip');
  await page.keyboard.insertText('紧随图片');
  assert.match(await editor.innerText(),/紧随图片后文/);
  check('typing continues directly after the inserted image');
  await page.screenshot({path:'docs/verification/composer-desktop.png'});
  await page.getByRole('button',{name:'会话模型：',exact:false}).click();
  const menu = page.getByRole('dialog',{name:'会话模型',exact:true});
  const rect = await menu.boundingBox(); const trigger = await page.getByRole('button',{name:'会话模型：',exact:false}).boundingBox();
  assert.ok(rect.y+rect.height<=trigger.y);
  await page.getByRole('textbox',{name:'搜索已配置模型'}).fill('no-such-model');
  await page.getByText('没有匹配的模型').waitFor();
  await page.getByRole('textbox',{name:'搜索已配置模型'}).fill('demo');
  await page.screenshot({path:'docs/verification/composer-model-menu.png'});
  await page.keyboard.press('Escape'); assert.equal(await menu.count(),0);
  check('model menu opens upward, searches, Escape closes and restores trigger focus');
  await page.getByRole('button',{name:'执行模式：ReAct',exact:true}).click();
  await page.getByRole('radio',{name:/Plan/}).click();
  await page.getByRole('button',{name:'执行模式：Plan',exact:true}).waitFor();
  check('mode selection uses compact upward menu');
  await page.getByRole('button',{name:'删除附件 示意图片.png',exact:true}).click();
  assert.equal(await editor.innerText(),'前文紧随图片后文');
  await editor.press('Control+z'); await page.locator('.inline-attachment.ready').waitFor();
  await editor.press('Control+Shift+z'); assert.equal(await page.locator('.inline-attachment').count(),0);
  await editor.press('Control+z'); await page.locator('.inline-attachment.ready').waitFor();
  check('remove, undo and redo preserve neighboring text and ready upload state');
  await page.reload(); await page.locator('.inline-attachment.ready').waitFor();
  assert.match(await editor.innerText(),/紧随图片后文/);
  check('reload restores ordered draft and ready attachment');
  await page.getByRole('button',{name:'删除附件 示意图片.png',exact:true}).click();
  await editor.fill('第一行'); await editor.press('End'); await editor.press('Enter'); await page.keyboard.insertText('第二行');
  assert.equal(await editor.innerText(),'第一行\n第二行');
  check('Enter inserts a newline rather than submitting');
  await editor.fill('ABCDEF'); await editor.press('Home'); await editor.press('ArrowRight');
  await editor.press('Shift+ArrowRight'); await editor.press('Shift+ArrowRight');
  await pasteImage('替换选区.png'); await page.locator('.inline-attachment.ready').waitFor();
  order = await editor.evaluate(el=>Array.from(el.childNodes).map(n=>n.nodeType===3?n.textContent:n.querySelector('.attachment-name')?.textContent));
  assert.deepEqual(order,['A','替换选区.png','DEF']);
  check('image paste replaces the active text selection');
  await editor.press('Control+End');
  await page.getByLabel('选择附件', {exact:true}).setInputFiles({name:'测试文件.txt',mimeType:'text/plain',buffer:Buffer.from('附件验证')});
  await page.locator('.inline-attachment.ready').nth(1).waitFor();
  check('file picker adds a normal file at the remembered caret');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'docs/verification/composer-mobile.png'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.getByRole('button',{name:'会话模型：',exact:false}).click();
  const narrow = await menu.boundingBox(); assert.ok(narrow.x>=0 && narrow.x+narrow.width<=390);
  await page.screenshot({path:'docs/verification/composer-mobile-menu.png'});
  await page.keyboard.press('Escape');
  check('390px layout and upward menu fit the viewport');
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('button',{name:'删除附件 替换选区.png',exact:true}).click();
  await page.getByRole('button',{name:'删除附件 测试文件.txt',exact:true}).click();
  await page.getByRole('button',{name:'执行模式：Plan',exact:true}).click();
  await page.getByRole('radio',{name:/ReAct/}).click();
  await editor.fill('失败后重试');
  let failOnce = true;
  await page.route('**/api/artifacts', async route => {
    if (failOnce) { failOnce=false; await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'TEST_UPLOAD_FAILURE',message:'测试上传失败'}})}); }
    else await route.continue();
  });
  await pasteImage('重试图片.png'); await page.locator('.inline-attachment.failed').waitFor();
  assert.ok(await page.getByRole('button',{name:'发送任务',exact:true}).isDisabled());
  await page.getByRole('button',{name:'重试上传 重试图片.png',exact:true}).click();
  await page.locator('.inline-attachment.ready').waitFor();
  await page.unroute('**/api/artifacts');
  await page.getByRole('button',{name:'删除附件 重试图片.png',exact:true}).click();
  check('failed upload blocks send; retry resolves the original chip');
  await editor.fill('前后'); await editor.press('Home'); await editor.press('ArrowRight');
  let release;
  const gate = new Promise(resolve=>{release=resolve;});
  await page.route('**/api/artifacts',async route=>{await gate; await route.continue();});
  await pasteImage('已删除图片.png'); await page.locator('.inline-attachment.uploading').waitFor();
  const finished = page.waitForResponse(r=>r.url().endsWith('/api/artifacts'));
  await page.getByRole('button',{name:'删除附件 已删除图片.png',exact:true}).click(); release();
  await finished; await page.unroute('**/api/artifacts');
  await page.waitForTimeout(100);
  assert.equal(await page.locator('.inline-attachment').count(),0);
  assert.equal(await editor.innerText(),'前后');
  check('deleting an uploading chip prevents late completion from restoring it');
  await editor.fill('输入框连续编辑验收');
  await editor.press('Control+Enter');
  await page.getByText('任务已由服务端受理。',{exact:false}).waitFor();
  await page.waitForFunction(()=>document.querySelector('.inline-editor')?.textContent==='');
  check('Ctrl+Enter submits to real isolated service and clears draft after acceptance');
  assert.deepEqual(errors,[]);
  fs.writeFileSync('docs/verification/composer-browser.json',JSON.stringify({date:new Date().toISOString(),browser:'Edge headless',service:'isolated real FastAPI/SQLite/Demo',checks,errors,imagePaste:'ClipboardEvent with File; real upload endpoint',userDataModified:false},null,2));
} catch (error) {
  await page.screenshot({path:'docs/verification/composer-failure.png'});
  console.error(await page.locator('body').innerText());
  throw error;
} finally {await browser.close();}
